# Generated by Django 5.1.4 on 2025-01-25 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150, verbose_name="Название статьи")),
                ("text", models.TextField(blank=True, null=True, verbose_name="статья")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images_aticle/", verbose_name="превью статьи"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="дата последнего изменения")),
                ("date_published", models.DateTimeField(auto_now_add=True, verbose_name="дата публикации")),
                ("published", models.BooleanField(default=True)),
                ("number_of_views", models.IntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name="Автор"
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья>",
                "verbose_name_plural": "Статьи",
                "ordering": ["date_published"],
            },
        ),
    ]
