# Generated by Django 5.1.4 on 2025-02-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150, verbose_name="Название статьи")),
                ("text", models.TextField(blank=True, null=True, verbose_name="статья")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images_aticle/", verbose_name="превью статьи"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="дата последнего изменения")),
                ("date_published", models.DateTimeField(verbose_name="дата публикации")),
                ("published", models.BooleanField(default=True, verbose_name="Опубликовано")),
                ("number_of_views", models.IntegerField(default=0, verbose_name="Количество просмотров")),
            ],
            options={
                "verbose_name": "Статья>",
                "verbose_name_plural": "Статьи",
                "ordering": ["-date_published"],
            },
        ),
    ]
