# Generated by Django 5.1.4 on 2025-01-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_blog_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="date_published",
            field=models.DateTimeField(verbose_name="дата публикации"),
        ),
    ]
