# Generated by Django 5.1.4 on 2025-01-26 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_article_date_published"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-date_published"], "verbose_name": "Статья>", "verbose_name_plural": "Статьи"},
        ),
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="number_of_views",
            field=models.IntegerField(default=0, verbose_name="Количество просмотров"),
        ),
        migrations.AlterField(
            model_name="article",
            name="published",
            field=models.BooleanField(default=True, verbose_name="Опубликовано"),
        ),
    ]
