# Generated by Django 5.1.4 on 2025-02-09 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category_name", models.CharField(max_length=150, verbose_name="категория")),
                ("description", models.TextField(blank=True, null=True, verbose_name="описание")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images_cat/", verbose_name="изображение"),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["category_name"],
            },
        ),
        migrations.CreateModel(
            name="PageBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150, verbose_name="Название блока")),
                ("text", models.TextField(blank=True, null=True, verbose_name="текстовой блок")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="дата создания")),
                ("updated_at", models.DateTimeField(auto_now_add=True, verbose_name="дата последнего изменения")),
            ],
            options={
                "verbose_name": "Текстовой Блок",
                "verbose_name_plural": "Текстовые Блоки",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="наименование")),
                ("description", models.TextField(verbose_name="описание")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images_products/",
                        validators=[django.core.validators.FileExtensionValidator(["png", "jpg"])],
                        verbose_name="изображение",
                    ),
                ),
                ("price", models.IntegerField(verbose_name="цена")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="дата последнего изменения")),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["created_at"],
            },
        ),
    ]
