# Generated by Django 5.1.4 on 2025-02-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="unpublish_product",
            field=models.CharField(
                choices=[("published", "Опубликовано"), ("unpublished", "Остановлено"), ("pending", "На утверждении")],
                default="pending",
                max_length=17,
                verbose_name="наименование",
            ),
        ),
    ]
