# Generated by Django 5.1.4 on 2025-02-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_unpublish_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["created_at"],
                "permissions": [("can_unpublish_product", "Может отменять публикацию продукта")],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
