# Generated by Django 5.1.4 on 2025-01-14 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_category_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PageBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150, verbose_name="Название блока")),
                ("text", models.TextField(blank=True, null=True, verbose_name="текстовой блок")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="дата создания")),
                ("updated_at", models.DateTimeField(auto_now_add=True, verbose_name="дата последнего изменения")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name="Автор"
                    ),
                ),
            ],
            options={
                "verbose_name": "Текстовой Блок",
                "verbose_name_plural": "Текстовые Блоки",
                "ordering": ["created_at"],
            },
        ),
    ]
