# Generated by Django 5.1.4 on 2025-01-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_pageblock"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images_cat/", verbose_name="изображение"),
        ),
    ]
